### ISSUE TITLE
Does not seem to be compatible with Azure Artifacts

### ISSUE THREAD

**Issue by bbrandt** [taori/NugetUnlister#25]
```ps
PS C:\src> nuget-unlist drop like MyCompany.Azure ".*" foo --source https://myorg.pkgs.visualstudio.com/Proj/_packaging/MyPackage/nuget/v3/
Loading packages from "https://api.nuget.org/v3-flatcontainer/MyPackage/index.json".
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
```

Azure Artifacts does support the `nuget delete` syntax:
https://learn.microsoft.com/en-us/azure/devops/artifacts/how-to/delete-and-recover-packages?view=azure-devops&tabs=nuget#unlist-packages-using-nugetexe

**Comment by taori** [comment]
Sorry for the late response - Only just noticed this. Did you also specify a key for the command? I did not yet have to use this tool with private package sources, but if the output is correct, it appears it is trying to access a different package store, which does not make sense for the parameters you provided. I will provide a patch shortly.

**Comment by taori** [comment]
Feel free to retry with NugetUnlister.2.2.2-beta58

Note the following code snippet:

```cs
			url = feedUrl == null
				? $@"https://api.nuget.org/v3-flatcontainer/{packageName}/index.json"
				: $@"{feedUrl.TrimEnd('/')}/{packageName}/index.json";
```

The source you specify should look similar to https://api.nuget.org/v3-flatcontainer/{packageName}/index.json. If you can access that url with your browser, the tool should be able to work properly. Let me know if it works.

**Comment by bbrandt** [comment]
Yes.  Looks like we got one step closer.  The next thing to figure out I believe is how to have the tool call the credential provider.
https://github.com/microsoft/artifacts-credprovider

For now, I've solved my problem with PowerShell in an Azure DevOps pipeline, so no need to keep working through this just for me.

**Comment by taori** [comment]
What exactly does the credential provider do though? Most i have used are interactive tools and therefore not really an option for being included in a call chain, since this is a CI tool. What i could do however is dumping the list of nuget commands, so that each line of commands can be modified on CI side where further processing can happen. Unfortunately i have not worked with the artifacts credprovider so i don't know. Are you using the tool at all now? I would at least want it to be helpful in automating the process even if it isn't doing credentials itself
